clk: cix: Add missing bitfield.h include
Add the missing "#include <linux/bitfield.h>" to fix follow errors:
  drivers/clk/cix/clk-sky1-audss.c: In function ‘sky1_audss_clk_probe’:
  drivers/clk/cix/clk-sky1-audss.c:1045:16: error: implicit declaration of function ‘FIELD_PREP’ [-Werror=implicit-function-declaration]
   1045 |                FIELD_PREP(SKY1_AUDSS_RCSU_TIMEOUT_MASK, SKY1_AUDSS_RCSU_TIMEOUT_VAL),
        |                ^~~~~~~~~~
  cc1: all warnings being treated as errors

Fixes: 8b9beff06f8d ("clk: cix: add sky1-audss and acpi clk drivers.")
Signed-off-by: WangYuli <wangyuli@uniontech.com>