soc: cix: Add missing memblock.h include
Add the missing "#include <linux/memblock.h>" to fix follow errors:

  drivers/soc/cix/acpi/reserved_memory.c: In function ‘reserved_mem_handler’:
  drivers/soc/cix/acpi/reserved_memory.c:51:25: error: implicit declaration of function ‘memblock_mark_nomap’ [-Werror=implicit-function-declaration]
     51 |                         memblock_mark_nomap(rmem->base, rmem->size);
        |                         ^~~~~~~~~~~~~~~~~~~
  drivers/soc/cix/acpi/reserved_memory.c:53:25: error: implicit declaration of function ‘memblock_reserve’ [-Werror=implicit-function-declaration]
     53 |                         memblock_reserve(rmem->base, rmem->size);
        |                         ^~~~~~~~~~~~~~~~
  cc1: all warnings being treated as errors

  drivers/soc/cix/acpi/acpi_resource_lookup.c: In function ‘rmem_dev_set_dma’:
  drivers/soc/cix/acpi/acpi_resource_lookup.c:179:14: error: implicit declaration of function ‘memblock_is_region_memory’ [-Werror=implicit-function-declaration]
    179 |         if (!memblock_is_region_memory(base, size)
        |              ^~~~~~~~~~~~~~~~~~~~~~~~~
  drivers/soc/cix/acpi/acpi_resource_lookup.c:180:20: error: implicit declaration of function ‘memblock_is_map_memory’ [-Werror=implicit-function-declaration]
    180 |                 || memblock_is_map_memory(base))
        |                    ^~~~~~~~~~~~~~~~~~~~~~
  cc1: all warnings being treated as errors

Fixes: 954d134cacf9 ("soc: cix: add acpi support for Cix platform.")
Signed-off-by: WangYuli <wangyuli@uniontech.com>