drm: cix: Only use mode and clk_rate when !CONFIG_DRM_LINLONDP_CLOCK_FIXED
Fix follow errors when !CONFIG_DRM_LINLONDP_CLOCK_FIXED:
  drivers/gpu/drm/cix/linlon-dp/linlondp_crtc.c: In function ‘linlondp_crtc_prepare’:
  drivers/gpu/drm/cix/linlon-dp/linlondp_crtc.c:127:34: error: unused variable ‘mode’ [-Werror=unused-variable]
    127 |         struct drm_display_mode *mode = &kcrtc_st->base.adjusted_mode;
        |                                  ^~~~
  drivers/gpu/drm/cix/linlon-dp/linlondp_crtc.c: In function ‘linlondp_crtc_mode_fixup’:
  drivers/gpu/drm/cix/linlon-dp/linlondp_crtc.c:547:23: error: unused variable ‘clk_rate’ [-Werror=unused-variable]
    547 |         unsigned long clk_rate;
        |                       ^~~~~~~~
  cc1: all warnings being treated as errors

Fixes: 08471690a924 ("drm: cix: add drm driver for CiX platforms.")
Signed-off-by: WangYuli <wangyuli@uniontech.com>