mtd: Remove an unused-variable adev
There was an unused-variable 'adev' brings a warning.

Resolve following error when '-Werror' was enabled:

drivers/mtd/mtdpart.c: In function ‘mtd_part_acpi_parse’:
drivers/mtd/mtdpart.c:584:29: error: unused variable ‘adev’ [-Werror=unused-variable]
  584 |         struct acpi_device *adev;
      |                             ^~~~
cc1: all warnings being treated as errors

Reported-by: Mingcong Bai <baimingcong@uniontech.com>
Signed-off-by: WangYuli <wangyuli@uniontech.com>