LoongArch: KVM: Add PV IPI support on host side
commit e33bda7ee50c ("LoongArch: KVM: Add PV IPI support on host side")
Conflict: none
Backport-reason: Synchronize upstream linux loongarch kvm
patch to support loongarch virtualization.
Checkpatch: no, to be consistent with upstream commit.

On LoongArch system, ipi hw uses iocsr registers, there is one iocsr
register access on ipi sending, and two iocsr access on ipi receiving
which is ipi interrupt handler. On VM mode all iocsr accessing will
cause VM to trap into hypervisor. So with one ipi hw notification
there will be three times of trap.

PV ipi is added for VM, hypercall instruction is used for ipi sender,
and hypervisor will inject SWI to destination vcpu. During SWI interrupt
handler, only estat CSR register is written to clear irq. Estat CSR
register access will not trap into hypervisor. So with pv ipi supported,
there is one trap with pv ipi sender, and no trap with ipi receiver,
there is only one trap with ipi notification.

Also this patch adds ipi multicast support, the method is similar with
x86. With ipi multicast support, ipi notification can be sent to at most
128 vcpus at one time. It reduces trap times into hypervisor greatly.

Signed-off-by: Bibo Mao <maobibo@loongson.cn>
Signed-off-by: Xianglai Li <lixianglai@loongson.cn>

LoongArch: KVM: Fix unknown register name 'v0' in asm

According to KVM documention for LoongArch, 'v0' should be 'a0'.
And 'a0' has been there upstream.

Fix follow compile errors with clang-19:

In file included from ./include/uapi/linux/kvm_para.h:41:
./arch/loongarch/include/asm/kvm_para.h:44:24: error: unknown register name 'v0' in asm
   44 |         register long ret asm("v0");
      |                               ^
./arch/loongarch/include/asm/kvm_para.h:59:24: error: unknown register name 'v0' in asm
   59 |         register long ret asm("v0");
      |                               ^
./arch/loongarch/include/asm/kvm_para.h:76:24: error: unknown register name 'v0' in asm
   76 |         register long ret asm("v0");
      |                               ^
./arch/loongarch/include/asm/kvm_para.h:94:24: error: unknown register name 'v0' in asm
   94 |         register long ret asm("v0");
      |                               ^
./arch/loongarch/include/asm/kvm_para.h:114:24: error: unknown register name 'v0' in asm
  114 |         register long ret asm("v0");
      |                               ^
./arch/loongarch/include/asm/kvm_para.h:135:24: error: unknown register name 'v0' in asm
  135 |         register long ret asm("v0");
      |                               ^
6 errors generated.

Link: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=e33bda7ee50c3c20d80f5ca6dc5ca2cd37863518
Signed-off-by: Mingcong Bai <baimingcong@uniontech.com>
Signed-off-by: WangYuli <wangyuli@uniontech.com>
Squash-merge: 1461dde2af06 LoongArch: KVM: Add PV IPI support on host side
Squash-merge: b92a7f866963 LoongArch: KVM: Fix unknown register name 'v0' in asm