deepin: ASoC: qcom: sc8280xp: Convert asoc_rtd_to_cpu to snd_soc_rtd_to_cpu
Commit ea78b26ffebf ("ASoC: remove asoc_xxx() compatible macro") in
deepin-kernel removes asoc_xxx() compatible macro.

Fix follow errors:
  sound/soc/qcom/sc8280xp.c: In function ‘sc8280xp_snd_init’:
  sound/soc/qcom/sc8280xp.c:30:39: error: implicit declaration of function ‘asoc_rtd_to_cpu’; did you mean ‘snd_soc_rtd_to_cpu’? [-Werror=implicit-function-declaration]
     30 |         struct snd_soc_dai *cpu_dai = asoc_rtd_to_cpu(rtd, 0);
        |                                       ^~~~~~~~~~~~~~~
        |                                       snd_soc_rtd_to_cpu
  sound/soc/qcom/sc8280xp.c:30:39: error: initialization of ‘struct snd_soc_dai *’ from ‘int’ makes pointer from integer without a cast [-Werror=int-conversion]
  cc1: all warnings being treated as errors

Signed-off-by: WangYuli <wangyuli@uniontech.com>