drm/arise: cbios: Prune unreachable code
As ulTemp is declared as CBIOS_U32, it cannot <126 and >125 at the
same time.

Fix follow error with clang-19:

drivers/gpu/drm/arise/cbios/Util/CBiosUtil.c:55:25: error: overlapping comparisons always evaluate to false [-Werror,-Wtautological-overlap-compare]
   55 |     else if((ulTemp<126)&&(ulTemp>125))
      |             ~~~~~~~~~~~~^~~~~~~~~~~~~~
1 error generated.

Signed-off-by: WangYuli <wangyuli@uniontech.com>