Revert "AOSCOS: staging: sb105x: revise type of second argument of mp_send_xchar() as u8"
This reverts commit 30ea1986445ffd53a993d4cb0b281cab1b65ba72.

Commit 3a00da027946 ("tty: make tty_operations::send_xchar accept u8
char") does exists in linux-6.6.y LTS tree.

Just drop this fix for v6.6.

Fix follow error:
  drivers/staging/sb105x/sb_pci_mp.c:1703:27: error: initialization of ‘void (*)(struct tty_struct *, char)’ from incompatible pointer type ‘void (*)(struct tty_struct *, u8)’ {aka ‘void (*)(struct tty_struct *, unsigned char)’} [-Werror=incompatible-pointer-types]
   1703 |         .send_xchar     = mp_send_xchar,
        |                           ^~~~~~~~~~~~~
  drivers/staging/sb105x/sb_pci_mp.c:1703:27: note: (near initialization for ‘sb_mp_ops.send_xchar’)
  cc1: all warnings being treated as errors

Reported-by: Lunpeng Wen <wenlunpeng@uniontech.com>
Signed-off-by: WangYuli <wangyuli@uniontech.com>