sh: hd64461: Make setup_hd64461() static
mainline:1e21acb7fbfb15fcb4afe21fb5a50a1bc00743ec
severity: Moderate

upstream commit 1e21acb7fbfb15fcb4afe21fb5a50a1bc00743ec ("sh: hd64461: Make setup_hd64461() static")

Enforce internal linkage for setup_hd64461().

This fixes the following error:
arch/sh/cchips/hd6446x/hd64461.c:75:12: error: no previous prototype for 'setup_hd64461' [-Werror=missing-prototypes]

Intel-SIG: commit 1e21acb7fbfb ("sh: hd64461: Make setup_hd64461() static")

Signed-off-by: Artur Rojek <contact@artur-rojek.eu>
Reviewed-by: John Paul Adrian Glaubitz <glaubitz@physik.fu-berlin.de>
Link: https://lore.kernel.org/r/20240211193451.106795-1-contact@artur-rojek.eu
Signed-off-by: John Paul Adrian Glaubitz <glaubitz@physik.fu-berlin.de>
[ Quanxian Wang: amend commit log ]
Signed-off-by: Quanxian Wang <quanxian.wang@intel.com>