drm: cix: Add missing irq.h include
Add the missing "#include <linux/irq.h>" to fix follow errors:
  drivers/gpu/drm/cix/dptx/trilin_dptx.c: In function ‘trilin_dp_init_config’:
  drivers/gpu/drm/cix/dptx/trilin_dptx.c:2611:9: error: implicit declaration of function ‘irq_set_status_flags’ [-Werror=implicit-function-declaration]
   2611 |         irq_set_status_flags(dp->irq, IRQ_DISABLE_UNLAZY);
        |         ^~~~~~~~~~~~~~~~~~~~
  drivers/gpu/drm/cix/dptx/trilin_dptx.c:2611:39: error: ‘IRQ_DISABLE_UNLAZY’ undeclared (first use in this function)
   2611 |         irq_set_status_flags(dp->irq, IRQ_DISABLE_UNLAZY);
        |                                       ^~~~~~~~~~~~~~~~~~
  drivers/gpu/drm/cix/dptx/trilin_dptx.c:2611:39: note: each undeclared identifier is reported only once for each function it appears in
  cc1: all warnings being treated as errors

Fixes: 08471690a924 ("drm: cix: add drm driver for CiX platforms.")
Signed-off-by: WangYuli <wangyuli@uniontech.com>